<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-13T18:29:56 IST" name="Default suite" finished-at="2025-06-13T18:30:01 IST" duration-ms="4841">
    <groups>
    </groups>
    <test started-at="2025-06-13T18:29:56 IST" name="Default test" finished-at="2025-06-13T18:30:01 IST" duration-ms="4841">
      <class name="API.Test.member_Test">
        <test-method signature="Loginaccess_token()[pri:0, instance:API.Test.member_Test@61230f6a]" started-at="2025-06-13T18:29:56 IST" name="Loginaccess_token" finished-at="2025-06-13T18:29:59 IST" duration-ms="3539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginaccess_token -->
        <test-method signature="Testlistofmember()[pri:1, instance:API.Test.member_Test@61230f6a]" started-at="2025-06-13T18:29:59 IST" name="Testlistofmember" finished-at="2025-06-13T18:30:00 IST" duration-ms="598" status="FAIL">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["data"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["data"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at org.json.JSONObject.getJSONObject(JSONObject.java:780)
at API.Test.member_Test.Testlistofmember(member_Test.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testlistofmember -->
        <test-method signature="Testviewmember()[pri:2, instance:API.Test.member_Test@61230f6a]" started-at="2025-06-13T18:30:00 IST" name="Testviewmember" finished-at="2025-06-13T18:30:01 IST" duration-ms="622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testviewmember -->
      </class> <!-- API.Test.member_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
